### ISSUE TITLE
hey man i cant make my custom splash work 

### ISSUE THREAD

**Issue by theSkonk** [atomgomba/bflogoreplacer#1]
![diary](https://user-images.githubusercontent.com/36688793/41975389-e5aeaf5e-7a5d-11e8-9a59-91abb9bd214a.png)

any ideas? I'm using 000000 and ffffff for my txt but it wont upload

**Comment by Docteh** [comment]
Hopefully you got this solved, but that green isn't green enough. needs to be 255, not just 249.
